linters:
  enable:
    - bodyclose         # checks whether HTTP response body is closed successfully -
    - deadcode          # Finds unused code
    - depguard          # Go linter that checks if package imports are in a list of acceptable packages
    - dogsled           # Checks assignments with too many blank identifiers (e.g. x, _, _, _, := f())
    - errcheck          # Errcheck is a program for checking for unchecked errors in go programs
    - funlen            # Tool for detection of long functions
    - gochecknoglobals  # Checks that no globals are present in Go code
    - gochecknoinits    # Checks that no init functions are present in Go code
    - goconst           # Finds repeated strings that could be replaced by a constant
    - gocritic          # The most opinionated Go source code linter
    - gocyclo           # Computes and checks the cyclomatic complexity of functions
    - godox             # Tool for detection of FIXME, TODO and other comment keywords
    - gofmt             # Gofmt checks whether code was gofmt-ed. By default this tool runs with -s option to check for code simplification
    - goimports         # Goimports does everything that gofmt does. Additionally it checks unused imports
    - revive
    - gosec             # (gas): Inspects source code for security problems
    - gosimple          # Linter for Go source code that specializes in simplifying a code
    - govet             # (vet, vetshadow): Vet examines Go source code and reports suspicious constructs
    - ineffassign       # Detects when assignments to existing variables are not used
    - lll               # Reports long lines [fast: true, auto-fix: false]
    - govet
    - misspell          # Finds commonly misspelled English words in comments
    - nakedret          # Finds naked returns in functions greater than a specified function length
    - prealloc          # Finds slice declarations that could potentially be preallocated
    - exportloopref
    - staticcheck       # Staticcheck is a go vet on steroids, applying a ton of static analysis checks
    - structcheck       # Finds unused struct fields
    - stylecheck        # Stylecheck is a replacement for golint
    - typecheck         # Like the front-end of a Go compiler, parses and type-checks Go code
    - unconvert         # Remove unnecessary type conversions
    - unparam           # Reports unused function parameters
    - unused            # Checks Go code for unused constants, variables, functions and types
    - varcheck          # Finds unused global variables and constants [fast: true, auto-fix: false]
    - whitespace        # Tool for detection of leading and trailing whitespace [fast: true, auto-fix: true]

linters-settings:
  staticcheck:
    go: "1.16"
    checks: [ "all", "-SA1029"]
